baseURL = 'https://maktabah-al-hamdaniyyah.pages.dev/'
title = 'Maktabah Al-Hamdaniyyah'
theme = "blowfish"

# --- BAGIAN INI YANG BIKIN ERROR ---
# Kita harus mendefinisikan bahasa secara spesifik untuk Blowfish
defaultContentLanguage = "id"

[languages]
  [languages.id]
    languageCode = "id"
    contentDir = "content"
    languageName = "Bahasa Indonesia"
    weight = 1
# -----------------------------------

[params]
    colorScheme = "blowfish"
    showRecent = true
    header = "double" # Supaya menu navigasi terlihat jelas

[[menu.main]]
    name = "Pendidikan"
    url = "/categories/pendidikan"
    weight = 1

[[menu.main]]
    name = "Filosofi"
    url = "/categories/filosofi"
    weight = 2