baseURL = 'https://maktabah-al-hamdaniyyah.pages.dev/'
languageCode = 'id'
title = 'Maktabah Al-Hamdaniyyah'
theme = "newsroom"

[params]
    env = "production"
    title = "Maktabah Al-Hamdaniyyah"
    description = "Literasi, Pemikiran, dan Kebudayaan"
    author = "Ibn Shomad"
    primaryColor = "#cc0000"